global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'explorer-backend'

    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'explorer-backend'